itag: '&a&l! &e&lINFO'
itagst: '&a&l! &e&lINFO'
itags: '&a&l! &e&lINFO'
ptag: '&a&l! &e&lPlugins'
dtag: '&a&l! &e&lVersao'
atag: '&a&l! &e&lAjuda'
ctag: '&a&l! &e&lComandos'
ftag: '&a&l! &e&lFormulario'
vtag: '&a&l! &e&lVip'
stag: '&a&l! &e&lStaff'
stagD: '&a&l! &4Donos:'
stagSD: '&a&l! &4Sub Donos:'
stagA: '&a&l! &4Administradores:'
stagM: '&a&l! &dModeradores:'
stagH: '&a&l! &eAjudantes:'
Sp: '&4Sem players!'
info:
- '&b&m-------------------------------------------------------------------'
- '&e    Bem vindo %player% ao Sword art Online MC'
- '&eO servidor e baseado no anime com estilo de Rankup'
- '&e     Para mais informacoes utilize /comandos'
- '&b&m-------------------------------------------------------------------'
plugin:
- '&b&m-------------------------------------------------------------------'
- '&eOs plugins de nosso servidor sao inteiramente &6modificados'
- '&epelos nosso &6desinvolvedores&e, caso tenhao alguma duvida'
- '&epergunte ao administrador ou use &6/COMANDOS'
- '&b&m-------------------------------------------------------------------'
dev:
- '&b&m-------------------------------------------------------------------'
- '&6O Servidor está na versão: &e&oBeta 1.5.3'
- '&b&m-------------------------------------------------------------------'

ajuda:
- '&b&m-------------------------------------------------------------------'
- '&6&l%Player% &eesta com alguma duvida em nosso servidor?'
- '&eUse &a/Comandos &epara ver  os comandos ultilizados'
- '&eou pergunte para algum staff Online usando &6/Staff'
- '&b&m-------------------------------------------------------------------'

comandos:
- '&b&m-------------------------------------------------------------------'
- '&6/clan &f– &epara ver os comando de clans'
- '&6/trocas &f– &epara ver comandos de como trocar'
- '&6/leilao &f– &epara ver comandos de leilao'
- '&6/bonus diario'
- '&6/warp'
- '&6/terrenos'
- '&e&oOu acesse nosso site para ver os comandos'
- '&a&ohttps://comandos.saomc.co/'
- '&b&m--------------------------------------------------------------------'

formulario:
- '&b&m--------------------------------------------------------------------'
- '&ePreencha o formulario do link abaixo:'
- '  &a&ohttps://formulario.saomc.co/'
- '&b&m--------------------------------------------------------------------'
vip:
- '&b&m--------------------------------------------------------------------'
- '&6Vip Diario: &e2:90 &aUse para ver: /VIP VER DIARIO'
- '&6Vip Diario: &e14:90 &aUse para ver: /VIP VER SEMANAL'
- '&6Vip Diario: &e39:90 &aUse para ver: &/VIP VER MENSAL'
- '&aCompre Vip no nosso site:' 
- '&a&ohttps://Vips.saomc.co/'
- '&b&m--------------------------------------------------------------------'
site:
- '&b&m--------------------------------------------------------------------'
- '&6Vip Diario: &e2:90 &aUse para ver: /VIP VER DIARIO'
- '&6Vip Diario: &e14:90 &aUse para ver: /VIP VER SEMANAL'
- '&6Vip Diario: &e39:90 &aUse para ver: &/VIP VER MENSAL'
- '&aCompre Vip no nosso site:' 
- '&a&ohttps://Vips.saomc.co/'
- '&b&m--------------------------------------------------------------------'
social:
- '&b&m--------------------------------------------------------------------'
- '&6Vip Diario: &e2:90 &aUse para ver: /VIP VER DIARIO'
- '&6Vip Diario: &e14:90 &aUse para ver: /VIP VER SEMANAL'
- '&6Vip Diario: &e39:90 &aUse para ver: &/VIP VER MENSAL'
- '&aCompre Vip no nosso site:' 
- '&a&ohttps://Vips.saomc.co/'
- '&b&m--------------------------------------------------------------------'
regras:
- '&b&m--------------------------------------------------------------------'
- '&6Vip Diario: &e2:90 &aUse para ver: /VIP VER DIARIO'
- '&6Vip Diario: &e14:90 &aUse para ver: /VIP VER SEMANAL'
- '&6Vip Diario: &e39:90 &aUse para ver: &/VIP VER MENSAL'
- '&aCompre Vip no nosso site:' 
- '&a&ohttps://Vips.saomc.co/'
- '&b&m--------------------------------------------------------------------'
playlist:
- '&b&m--------------------------------------------------------------------'
- '&6Vip Diario: &e2:90 &aUse para ver: /VIP VER DIARIO'
- '&6Vip Diario: &e14:90 &aUse para ver: /VIP VER SEMANAL'
- '&6Vip Diario: &e39:90 &aUse para ver: &/VIP VER MENSAL'
- '&aCompre Vip no nosso site:' 
- '&a&ohttps://Vips.saomc.co/'
- '&b&m--------------------------------------------------------------------'