gb1:
- '&b&m-------------------------------------------------------------------'
- '&e    Bem vindo %player% ao Sword art Online MC'
- '&eO servidor e baseado no anime com estilo de Rankup'
- '&e     Para mais informacoes utilize /comandos'
- '&b&m-------------------------------------------------------------------'