name: HouseGuard
main: com.hg.HouseGuard
version: 0.2
depend: [WorldGuard, WorldEdit, Vault]
description: The best regions of your server! Using economy system, and permissions!
author: [Yarkhs, AtomGamers]
website: dev.bukkit.org/bukkit-plugins/houseguard/
commands:
  houseguard:
    aliases: ['hg', 'house', 'casa', 'area']
    description: HouseGuard - Principal Command