tag: '&a&l! &e&lHACK DECTADO'
tela:
- '&b&m-------------------------------------------------------------------'
- '&e    Ola %player% por favor abra o ant-cheat!'
- '&e             se deslogar serar banido!'
- '&b&m-------------------------------------------------------------------'